rephrase_sentences = {
  "LIVING_ROOM_SCENE2_put_both_the_alphabet_soup_and_the_tomato_sauce_in_the_basket": [
    "Kindly inspect the basket for the alphabet soup and the tangy tomato mix.",
    "The basket is the place where the lettered noodles and tomato blend reside.",
    "The basket cradles the ABC pasta and savory tomato relish, please.",
    "You'll find the letter soup and zesty tomato sauce inside the basket.",
    "Check the basket to see the lettered pasta and rich tomato mix.",
    "The alphabet soup and the tomato base are nestled together in the basket.",
    "Inside the basket, you'll come across both letter noodles and tomato puree.",
    "The basket shelters the lettered soup and tomato condiment.",
    "The letter pasta and tomato sauce rest in the basket.",
    "The letter broth and tomato paste are tucked in the basket.",
    "Please search the basket for the alphabet soup and tomato mixture.",
    "Kindly see the basket for the text noodles and the tomato blend.",
    "In the basket, you'll find the character pasta and tomato dressing.",
    "The basket is home to the letter noodles and tangy ketchup, please.",
    "Locate the typography pasta and rich red paste in the basket.",
    "Within the basket, you'll find the font pasta and zesty tomato mix.",
    "The basket holds the lettered noodles and tomato base nestled together.",
    "Inside the basket, you'll find both the character soup and tomato condiment.",
    "The basket cradles the font pasta and savory tomato blend.",
    "The letter pasta and tomato sauce can be discovered in the basket.",
    "The text noodles and tomato dressing await in the basket.",
    "Please investigate the basket for the alphabet pasta and tomato sauce.",
    "Kindly examine the basket for the lettered noodles and tomato puree.",
    "The basket contains the typography pasta and rich red paste.",
    "The basket houses the font pasta and zesty tomato relish, please.",
    "You'll locate the text noodles and savory tomato base inside the basket.",
    "Check the basket for the letter soup and tomato condiment.",
    "The alphabet noodles and tomato mix are snug within the basket.",
    "Inside the basket, you'll uncover the ABC pasta and tomato sauce.",
    "The basket holds the lettered pasta and savory tomato blend.",
    "The text pasta and tomato dressing can be found in the basket.",
    "The letter soup and tomato paste are stored in the basket.",
    "Please look in the basket for the alphabet soup and tomato puree.",
    "Kindly check the basket for the character pasta and tomato dressing.",
    "In the basket, you'll find the lettered pasta and tomato mix.",
    "The basket cradles the ABC noodles and savory tomato sauce, please.",
    "Locate the letter noodles and rich tomato base in the basket.",
    "Within the basket, you'll find the alphabet soup and tomato condiment.",
    "The lettered pasta and tomato blend are snug within the basket.",
    "Inside the basket, you'll find the text noodles and tomato sauce.",
    "The basket shelters the lettered broth and savory tomato mix.",
    "The character soup and tomato dressing can be discovered in the basket.",
    "The text pasta and tomato puree are tucked in the basket.",
    "Please examine the basket for the letter soup and tomato base.",
    "Kindly search the basket for the alphabet pasta and tomato blend.",
    "In the basket, you'll uncover the lettered pasta and rich tomato sauce.",
    "The basket is home to the font pasta and tangy tomato mix, please.",
    "Locate the character soup and savory tomato base in the basket.",
    "Within the basket, you'll find the letter broth and tomato condiment.",
    "The alphabet noodles and tomato dressing are nestled together in the basket.",
    "Inside the basket, you'll discover the text pasta and tomato sauce.",
    "The basket shelters the lettered soup and savory tomato blend.",
    "The container of letter pasta and tomato mix can be found in the basket.",
    "The text noodles and tomato base await in the basket.",
    "Please see the basket for the alphabet soup and rich tomato dressing.",
    "Kindly search the basket for the typography pasta and tomato condiment.",
    "In the basket, you'll uncover the character pasta and tomato puree.",
    "The basket holds the lettered broth and savory tomato blend, please.",
    "Locate the letter noodles and rich tomato base inside the basket.",
    "Within the basket, you'll find the text pasta and zesty tomato sauce.",
    "The alphabet soup and tomato mix are nestled together in the basket.",
    "Inside the basket, you'll uncover the letter pasta and tomato condiment.",
    "The basket shelters the lettered soup and savory tomato dressing.",
    "The character soup and tomato base can be discovered in the basket.",
    "The text noodles and tomato mix are tucked in the basket.",
    "Please examine the basket for the letter pasta and rich tomato puree.",
    "Kindly investigate the basket for the lettered soup and tomato blend.",
    "In the basket, you'll find the alphabet pasta and tomato sauce.",
    "The basket cradles the text noodles and savory tomato base, please.",
    "Locate the lettered pasta and rich tomato condiment in the basket.",
    "Within the basket, you'll find the character soup and zesty tomato dressing.",
    "The alphabet noodles and tomato blend are snug within the basket.",
    "Inside the basket, you'll discover the text pasta and tomato sauce.",
    "The basket holds the lettered broth and savory tomato mix.",
    "The character pasta and tomato dressing can be found in the basket.",
    "The letter noodles and tomato puree are stored in the basket.",
    "Please look in the basket for the typography pasta and tomato base.",
    "Kindly check the basket for the font pasta and tomato sauce.",
    "In the basket, you'll find the character soup and savory tomato mix.",
    "The basket houses the lettered noodles and tangy tomato blend, please.",
    "Locate the alphabet soup and rich tomato base inside the basket.",
    "Within the basket, you'll find the text pasta and tomato condiment.",
    "The lettered broth and tomato dressing are nestled together in the basket.",
    "Inside the basket, you'll uncover the letter pasta and tomato sauce.",
    "The basket shelters the alphabet soup and savory tomato blend.",
    "The text noodles and tomato base can be discovered in the basket.",
    "The character soup and tomato dressing are tucked in the basket.",
    "Please search the basket for the lettered pasta and rich tomato mix."
  ],
  
  # [ chatgpt v1
  #   "Explore the basket to find the lettered broth and the tangy tomato mix.",
  #   "The lattice holder contains the alphabet pasta and the rich tomato blend.",
  #   "You'll find the ABC noodles and tomato relish in the container, kindly.",
  #   "The letter soup and the savory red sauce are located in the basket.",
  #   "Inside the wicker basket, you'll find the alphabet noodles and the tomato sauce.",
  #   "Remember to check the basket for the text pasta and the tangy tomato sauce.",
  #   "The letter pasta and the ketchup are kept inside the wicker basket, please.",
  #   "Notice the assorted lettered noodles with tomato puree inside this container.",
  #   "Please note that the character soup and the tomato dressing are in the bin.",
  #   "Be aware that the typography pasta and the red sauce are in the straw holder.",
  #   "You'll discover the font pasta and the tomato mixture in the woven basket.",
  #   "Investigate the container to find the lettered soup and the rich tomato condiment.",
  #   "The wicker holder holds the alphabet noodles and the tomato base.",
  #   "You'll locate the ABC soup and the tomato dip within the bin, kindly.",
  #   "The letter broth and the tomato sauce are placed in the basket.",
  #   "Inside the straw basket lies the letter soup and the tomato mixture.",
  #   "The text pasta and the savory tomato sauce are in the wicker container.",
  #   "The letter noodles and the tomato paste can be found in the basket, please.",
  #   "Observe the variety of lettered noodles and tomato puree in this container.",
  #   "Note that the character soup and the tomato condiment are in the bin.",
  #   "Be aware that the typography noodles and the red tomato sauce are in the wicker basket.",
  #   "You'll find the font noodles and the tangy tomato blend in the woven container.",
  #   "Check the container for the lettered broth and the tomato mix.",
  #   "The lattice basket has the alphabet pasta and the tomato blend.",
  #   "You'll locate the ABC noodles and the rich tomato dip in the bin, kindly.",
  #   "The letter soup and the tomato base are inside the basket.",
  #   "Inside the wicker basket, find the alphabet noodles and the tomato mix.",
  #   "Remember to look in the basket for the text pasta and the savory tomato sauce.",
  #   "The letter pasta and the tomato condiment are stored in the wicker basket, please.",
  #   "Notice the assorted lettered noodles with tomato puree inside this container.",
  #   "Please be aware that the character pasta and the tomato dressing are in the bin.",
  #   "Know that the typography noodles and the red sauce are in the straw holder.",
  #   "You'll discover the font pasta and the tomato mix in the woven basket.",
  #   "Explore the container to find the lettered soup and the rich tomato condiment.",
  #   "The wicker basket holds the alphabet noodles and the tomato base.",
  #   "You'll locate the ABC soup and the tomato dip within the bin, kindly.",
  #   "The letter broth and the tomato sauce are placed in the basket.",
  #   "Inside the straw basket lies the letter soup and the tomato mixture.",
  #   "The text pasta and the savory tomato sauce are in the wicker container.",
  #   "The letter noodles and the tomato paste can be found in the basket, please.",
  #   "Observe the variety of lettered noodles and tomato puree in this container.",
  #   "Note that the character soup and the tomato condiment are in the bin.",
  #   "Be aware that the typography noodles and the red tomato sauce are in the wicker basket.",
  #   "You'll find the font noodles and the tangy tomato blend in the woven container.",
  #   "Check the container for the lettered broth and the tomato mix.",
  #   "The lattice basket has the alphabet pasta and the tomato blend.",
  #   "You'll locate the ABC noodles and the rich tomato dip in the bin, kindly.",
  #   "The letter soup and the tomato base are inside the basket.",
  #   "Inside the wicker basket, find the alphabet noodles and the tomato mix.",
  #   "Remember to look in the basket for the text pasta and the savory tomato sauce.",
  #   "The letter pasta and the tomato condiment are stored in the wicker basket, please.",
  #   "Notice the assorted lettered noodles with tomato puree inside this container.",
  #   "Please be aware that the character pasta and the tomato dressing are in the bin.",
  #   "Know that the typography noodles and the red sauce are in the straw holder.",
  #   "You'll discover the font pasta and the tomato mix in the woven basket.",
  #   "Explore the container to find the lettered soup and the rich tomato condiment.",
  #   "The wicker basket holds the alphabet noodles and the tomato base.",
  #   "You'll locate the ABC soup and the tomato dip within the bin, kindly.",
  #   "The letter broth and the tomato sauce are placed in the basket.",
  #   "Inside the straw basket lies the letter soup and the tomato mixture.",
  #   "The text pasta and the savory tomato sauce are in the wicker container.",
  #   "The letter noodles and the tomato paste can be found in the basket, please.",
  #   "Observe the variety of lettered noodles and tomato puree in this container.",
  #   "Note that the character soup and the tomato condiment are in the bin.",
  #   "Be aware that the typography noodles and the red tomato sauce are in the wicker basket.",
  #   "You'll find the font noodles and the tangy tomato blend in the woven container.",
  #   "Check the container for the lettered broth and the tomato mix.",
  #   "The lattice basket has the alphabet pasta and the tomato blend.",
  #   "You'll locate the ABC noodles and the rich tomato dip in the bin, kindly.",
  #   "The letter soup and the tomato base are inside the basket.",
  #   "Inside the wicker basket, find the alphabet noodles and the tomato mix.",
  #   "Remember to look in the basket for the text pasta and the savory tomato sauce.",
  #   "The letter pasta and the tomato condiment are stored in the wicker basket, please.",
  #   "Notice the assorted lettered noodles with tomato puree inside this container.",
  #   "Please be aware that the character pasta and the tomato dressing are in the bin.",
  #   "Know that the typography noodles and the red sauce are in the straw holder.",
  #   "You'll discover the font pasta and the tomato mix in the woven basket.",
  #   "Explore the container to find the lettered soup and the rich tomato condiment.",
  #   "The wicker basket holds the alphabet noodles and the tomato base.",
  #   "You'll locate the ABC soup and the tomato dip within the bin, kindly.",
  #   "The letter broth and the tomato sauce are placed in the basket.",
  #   "Inside the straw basket lies the letter soup and the tomato mixture.",
  #   "The text pasta and the savory tomato sauce are in the wicker container.",
  #   "The letter noodles and the tomato paste can be found in the basket, please.",
  #   "Observe the variety of lettered noodles and tomato puree in this container.",
  #   "Note that the character soup and the tomato condiment are in the bin.",
  #   "Be aware that the typography noodles and the red tomato sauce are in the wicker basket.",
  #   "You'll find the font noodles and the tangy tomato blend in the woven container.",
  #   "Check the container for the lettered broth and the tomato mix."
  # ],
    # [
    # "A careful look into the basket will reveal the presence of linguine letters and a robust marinara.",
    # "The basket cradles an assortment of pasta alphabets and a rich tomato concoction.",
    # "Tucked within the basket's weave, one finds the playful shapes of noodle letters and a jar of tomato essence.",
    # "The basket harbors a whimsical collection of alphabet pasta and a savory tomato reduction.",
    # "Peering into the basket, one might spot the charming array of lettered pasta and a classic tomato coulis.",
    # "The basket contains a delightful medley of pasta characters and a homemade tomato sauce.",
    # "Within the basket's depths, the pasta alphabet and a traditional tomato gravy await discovery.",
    # "The basket presents a curated selection of alphabet noodles and a gourmet tomato sauce.",
    # "Nestled in the basket are the fun forms of ABC pasta and a velvety tomato sauce.",
    # "The basket offers a glimpse of pasta letters and a lovingly prepared tomato sauce.",
    # "A container of pasta letters and a complementary tomato sauce reside in the basket's embrace.",
    # "The basket serves as a repository for the alphabet pasta and a well-seasoned tomato sauce.",
    # "One will find the basket housing a playful pasta alphabet and a tangy tomato sauce.",
    # "The basket, a cornucopia of delights, includes the pasta alphabet and a luscious tomato sauce.",
    # "A container of alphabet pasta and a tomato sauce with a hint of basil are nestled within the basket.",
    # "The basket, a vessel of culinary treasures, holds the alphabet pasta and a sun-kissed tomato sauce.",
    # "Within the basket, the alphabet pasta and a tomato sauce infused with herbs rest side by side.",
    # "The basket, with its quaint charm, carries the alphabet pasta and a robust tomato sauce.",
    # "A peek into the basket might unveil the alphabet pasta and a tomato sauce that whispers of summer.",
    # "The basket, a keeper of comfort foods, safeguards the alphabet pasta and a heartwarming tomato sauce."
    # ],
  "LIVING_ROOM_SCENE2_put_both_the_cream_cheese_box_and_the_butter_in_the_basket": [
    "Kindly check the basket for the dairy spread box and the churned delight.",
    "The basket is where you'll find the creamy cheese package and the golden spread.",
    "The basket holds the soft cheese container and the butter, please.",
    "You would locate the cheese spread box and the dairy gold inside the basket.",
    "You'll see the smooth cheese package and the butter within the basket.",
    "The cheese block casing and the creamy delight are nestled within the basket.",
    "Inside the basket, you'll come across both the cheese tub and the butter.",
    "The cheese vessel and the butter rest in the basket.",
    "The container of cheese spread and the butter can be found in the basket.",
    "The soft cheese box and the butter are in the basket.",
    "Please look for the creamy cheese box and the butter inside the basket.",
    "Kindly inspect the basket for the cream cheese tub and the golden spread.",
    "The basket is where you'll find the cheese tub and the churned butter.",
    "The basket cradles the cheese block and the creamy butter, please.",
    "You'll find the cheese tub and the golden dairy inside the basket.",
    "Check the basket to see the cream cheese tub and the butter.",
    "The cheese container and the dairy delight are nestled together in the basket.",
    "Inside the basket, you'll come across both the cheese vessel and the butter.",
    "The basket shelters the creamy cheese and the golden churn.",
    "The soft cheese and the butter rest in the basket.",
    "The cheese block and the butter are tucked in the basket.",
    "Please search the basket for the cheese container and the butter.",
    "Kindly see the basket for the cheese tub and the golden delight.",
    "In the basket, you'll find the cream cheese and the butter.",
    "The basket is home to the cheese spread and the golden dairy, please.",
    "Locate the cheese box and the butter in the basket.",
    "Within the basket, you'll find the cheese container and the butter.",
    "The soft cheese and the golden spread are snug within the basket.",
    "Inside the basket, you'll uncover the cheese tub and the butter.",
    "The basket holds the cheese vessel and the butter.",
    "The creamy cheese and the butter can be discovered in the basket.",
    "The soft cheese and the golden spread await in the basket.",
    "Please investigate the basket for the cheese box and the butter.",
    "Kindly examine the basket for the cheese container and the churned butter.",
    "The basket contains the cheese tub and the golden dairy.",
    "The basket houses the soft cheese and the creamy butter, please.",
    "You'll locate the cheese container and the butter inside the basket.",
    "Check the basket for the creamy cheese and the golden delight.",
    "The cheese and the butter are snug within the basket.",
    "Inside the basket, you'll uncover the cheese spread and the butter.",
    "The basket shelters the cheese tub and the butter.",
    "The container of cheese and the butter can be discovered in the basket.",
    "The cheese block and the golden spread are tucked in the basket.",
    "Please see the basket for the cheese and the butter.",
    "Kindly search the basket for the creamy cheese and the golden dairy.",
    "In the basket, you'll uncover the soft cheese and the butter.",
    "The basket is home to the cheese and the golden spread, please.",
    "Locate the cheese and the butter inside the basket.",
    "Within the basket, you'll find the cheese container and the golden churn.",
    "The cheese and the butter are nestled together in the basket.",
    "Inside the basket, you'll discover the cheese and the butter.",
    "The basket shelters the cheese and the butter.",
    "The container of cheese and the butter can be found in the basket.",
    "The cheese and the golden dairy are stored in the basket.",
    "Please look in the basket for the cheese and the butter.",
    "Kindly check the basket for the cheese and the churned delight.",
    "In the basket, you'll find the cheese and the golden dairy.",
    "The basket cradles the cheese and the butter, please.",
    "Locate the cheese and the golden spread in the basket.",
    "Within the basket, you'll find the cheese and the butter.",
    "The cheese and the golden spread are snug within the basket.",
    "Inside the basket, you'll uncover the cheese and the golden churn.",
    "The basket shelters the cheese and the golden delight.",
    "The cheese and the butter can be discovered in the basket.",
    "The cheese and the golden dairy are tucked in the basket.",
    "Please examine the basket for the cheese and the golden spread.",
    "Kindly search the basket for the cheese and the butter.",
    "In the basket, you'll uncover the cheese and the golden churn.",
    "The basket holds the cheese and the golden dairy, please.",
    "Locate the cheese and the butter inside the basket.",
    "Within the basket, you'll find the cheese and the golden spread.",
    "The cheese and the butter are nestled together in the basket.",
    "Inside the basket, you'll discover the cheese and the butter.",
    "The basket shelters the cheese and the golden churn.",
    "The container of cheese and the butter can be discovered in the basket.",
    "The cheese and the golden dairy are stored in the basket.",
    "Please search the basket for the cheese and the butter.",
    "Kindly see the basket for the cheese and the golden churn.",
    "In the basket, you'll find the cheese and the golden dairy.",
    "The basket is home to the cheese and the golden spread, please.",
    "Locate the cheese and the butter inside the basket.",
    "Within the basket, you'll find the cheese and the golden churn.",
    "The cheese and the butter are snug within the basket.",
    "Inside the basket, you'll uncover the cheese and the golden dairy.",
    "The basket shelters the cheese and the golden spread.",
    "The cheese and the butter can be found in the basket.",
    "The cheese and the golden delight are stored in the basket.",
    "Please look in the basket for the cheese and the butter.",
    "Kindly check the basket for the cheese and the golden dairy."
  ],

  # [
  #   "Within the woven confines of the hamper, one can find a container of whipped cream cheese alongside a spread of cultured butter.",
  #   "The hamper, often a trove of various items, today holds a container of soft cheese and a spread of clarified butter.",
  #   "Nestled among the contents of the hamper, the container of creamy cheese and the spread of rich butter sit quietly.",
  #   "A container of spreadable cheese and a spread of unsalted butter reside within the hamper, awaiting use.",
  #   "The hamper serves as a temporary home to a container of smooth cheese and a spread of sweet cream butter.",
  #   "Amidst the assortment in the hamper, a container of fresh cheese and a spread of European-style butter can be discovered.",
  #   "The hamper, with its capacity to hold many things, currently includes a container of delicate cheese and a spread of artisanal butter.",
  #   "A peek into the hamper would reveal a container of spreadable curd and a spread of grass-fed butter, placed among other things.",
  #   "The container of velvety cheese and the spread of homemade butter are among the selected items placed within the hamper.",
  #   "In the hamper, there lies a container of softened cheese and a spread of creamery butter, part of the day's necessities.",
  #   "The hamper, acting as a keeper of provisions, contains a container of luxurious cream cheese and a spread of wholesome butter."
  # ]
  "KITCHEN_SCENE4_put_the_black_bowl_in_the_bottom_drawer_of_the_cabinet_and_close_it": [
    "If you look in the cabinet's enclosed lower drawer, you'll spot the azure chalice.",
    'The bottom-most closed cabinet compartment houses the crimson goblet.',
    "In the bottom compartment of the cabinet, there's an emerald cup, which drawer is closed.",
    'The amethyst bowl can be found in the bottom drawer of the cupboard, which is shut.',
    'The onyx dish is in the closed bottom drawer of the cabinet.',
    'You can locate the sapphire vessel within the closed bottom drawer of the cabinet.',
    "In the closed lower drawer of the cabinet, you'll find the cerulean flask.",
    'The amber mug is positioned in the closed bottom drawer of the cabinet.',
    'The ivory plate is sitting in the securely closed lower part of that cabinet.',
    "The jade pot is inside the cabinet's shut bottom drawer.",
    'Carefully check the closed lower drawer of the cabinet to find the cobalt urn.',
    "If you look in the cabinet's enclosed lower drawer, you'll spot the ruby cup.",
    'The bottom-most closed cabinet compartment houses the turquoise dish.',
    "In the bottom compartment of the cabinet, there's a violet vessel, which drawer is closed.",
    'The ebony bowl can be found in the bottom drawer of the cupboard, which is shut.',
    'The alabaster plate is in the closed bottom drawer of the cabinet.',
    'You can locate the aquamarine mug within the closed bottom drawer of the cabinet.',
    "In the closed lower drawer of the cabinet, you'll find the garnet goblet.",
    'The obsidian chalice is positioned in the closed bottom drawer of the cabinet.',
    'The pearl cup is sitting in the securely closed lower part of that cabinet.',
    "The maroon vessel is inside the cabinet's shut bottom drawer.",
    'Carefully check the closed lower drawer of the cabinet to find the silver flask.',
    "If you look in the cabinet's enclosed lower drawer, you'll spot the indigo mug.",
    'The bottom-most closed cabinet compartment houses the bronze urn.',
    "In the bottom compartment of the cabinet, there's a coral dish, which drawer is closed.",
    'The ochre pot can be found in the bottom drawer of the cupboard, which is shut.',
    'The jade cup is in the closed bottom drawer of the cabinet.',
    'You can locate the topaz chalice within the closed bottom drawer of the cabinet.',
    "In the closed lower drawer of the cabinet, you'll find the lavender goblet.",
    'The emerald vessel is positioned in the closed bottom drawer of the cabinet.',
    'The teal flask is sitting in the securely closed lower part of that cabinet.',
    "The garnet bowl is inside the cabinet's shut bottom drawer.",
    'Carefully check the closed lower drawer of the cabinet to find the fuchsia dish.',
    "If you look in the cabinet's enclosed lower drawer, you'll spot the azure goblet.",
    'The bottom-most closed cabinet compartment houses the copper cup.',
    "In the bottom compartment of the cabinet, there's a golden vessel, which drawer is closed.",
    'The cobalt urn can be found in the bottom drawer of the cupboard, which is shut.',
    'The silver dish is in the closed bottom drawer of the cabinet.',
    'You can locate the ivory plate within the closed bottom drawer of the cabinet.',
    "In the closed lower drawer of the cabinet, you'll find the sapphire flask.",
    'The amethyst mug is positioned in the closed bottom drawer of the cabinet.',
    'The ruby chalice is sitting in the securely closed lower part of that cabinet.',
    "The turquoise pot is inside the cabinet's shut bottom drawer.",
    'Carefully check the closed lower drawer of the cabinet to find the alabaster vessel.',
    "If you look in the cabinet's enclosed lower drawer, you'll spot the jade cup.",
    'The bottom-most closed cabinet compartment houses the pearl goblet.',
    "In the bottom compartment of the cabinet, there's an onyx bowl, which drawer is closed.",
    'The topaz flask can be found in the bottom drawer of the cupboard, which is shut.',
    'The coral dish is in the closed bottom drawer of the cabinet.',
    'You can locate the ochre pot within the closed bottom drawer of the cabinet.',
    "In the closed lower drawer of the cabinet, you'll find the bronze cup.",
    'The maroon vessel is positioned in the closed bottom drawer of the cabinet.',
    'The lavender goblet is sitting in the securely closed lower part of that cabinet.',
    "The emerald chalice is inside the cabinet's shut bottom drawer.",
    'Carefully check the closed lower drawer of the cabinet to find the teal urn.',
    "If you look in the cabinet's enclosed lower drawer, you'll spot the fuchsia dish.",
    'The bottom-most closed cabinet compartment houses the garnet bowl.',
    "In the bottom compartment of the cabinet, there's a coral dish, which drawer is closed.",
    'The ivory plate can be found in the bottom drawer of the cupboard, which is shut.',
    'The sapphire flask is in the closed bottom drawer of the cabinet.',
    'You can locate the amethyst mug within the closed bottom drawer of the cabinet.',
    "In the closed lower drawer of the cabinet, you'll find the ruby chalice.",
    'The turquoise pot is positioned in the closed bottom drawer of the cabinet.',
    'The alabaster vessel is sitting in the securely closed lower part of that cabinet.',
    "The jade cup is inside the cabinet's shut bottom drawer.",
    'Carefully check the closed lower drawer of the cabinet to find the pearl goblet.',
    "If you look in the cabinet's enclosed lower drawer, you'll spot the onyx bowl.",
    'The bottom-most closed cabinet compartment houses the topaz flask.',
    "In the bottom compartment of the cabinet, there's a coral dish, which drawer is closed.",
    'The ochre pot can be found in the bottom drawer of the cupboard, which is shut.',
    'The bronze cup is in the closed bottom drawer of the cabinet.',
    'You can locate the maroon vessel within the closed bottom drawer of the cabinet.',
    "In the closed lower drawer of the cabinet, you'll find the lavender goblet.",
    'The emerald chalice is positioned in the closed bottom drawer of the cabinet.',
    'The teal urn is sitting in the securely closed lower part of that cabinet.',
    "The fuchsia dish is inside the cabinet's shut bottom drawer.",
    'Carefully check the closed lower drawer of the cabinet to find the garnet bowl.',
    "If you look in the cabinet's enclosed lower drawer, you'll spot the cobalt urn.",
    'The bottom-most closed cabinet compartment houses the silver dish.',
    "In the bottom compartment of the cabinet, there's a coral dish, which drawer is closed.",
    'The ivory plate can be found in the bottom drawer of the cupboard, which is shut.',
    'The sapphire flask is in the closed bottom drawer of the cabinet.',
    'You can locate the amethyst mug within the closed bottom drawer of the cabinet.',
    "In the closed lower drawer of the cabinet, you'll find the ruby chalice.",
    'The turquoise pot is positioned in the closed bottom drawer of the cabinet.',
    'The alabaster vessel is sitting in the securely closed lower part of that cabinet.',
    "The jade cup is inside the cabinet's shut bottom drawer.",
    'Carefully check the closed lower drawer of the cabinet to find the pearl goblet.'
  ],
  "LIVING_ROOM_SCENE5_put_the_white_mug_on_the_left_plate_and_put_the_yellow_and_white_mug_on_the_right_plate": [
    "Kindly notice that the azure goblet rests on the left plate and the slightly emerald goblet on the right plate.",
    "The cobalt vessel resting on the left dish, accompanied by a pale jade vessel positioned on the adjacent dish.",
    "In this alignment, the left receptacle harbors a sapphire chalice, contrasted by the opposing mint-green chalice on the right.",
    "The left plate supports a cerulean cup, as a chartreuse cup resides atop the right.",
    "An indigo goblet on the left plate and a lightly-hued vessel placed on the right plate.",
    "On the left platter, you'll find the navy goblet, and on the right platter, there's an olive goblet.",
    "The left dish displays a periwinkle mug and the right dish holds a moss-green mug.",
    "The pure aqua chalice is placed to the left, while the lime-toned chalice occupies the right side.",
    "The azure vessel is on the left plate whereas the pale seafoam vessel is on the right plate.",
    "There's a turquoise goblet that lies on the left platter, distinct from an apple-green goblet found on the opposite one.",
    "The ultramarine cup is situated on the left dish, while the light olive cup is positioned on the right dish.",
    "Kindly notice that the crimson goblet rests on the left plate and the slightly amber goblet on the right plate.",
    "The ruby vessel resting on the left dish, accompanied by a pale golden vessel positioned on the adjacent dish.",
    "In this alignment, the left receptacle harbors a scarlet chalice, contrasted by the opposing champagne chalice on the right.",
    "The left plate supports a maroon cup, as a gold-hued cup resides atop the right.",
    "An ochre goblet on the left plate and a lightly-colored vessel placed on the right plate.",
    "On the left platter, you'll find the burgundy goblet, and on the right platter, there's an ivory goblet.",
    "The left dish displays a rose mug and the right dish holds a pale topaz mug.",
    "The pure carmine chalice is placed to the left, while the honey-toned chalice occupies the right side.",
    "The cherry vessel is on the left plate whereas the light amber vessel is on the right plate.",
    "There's a vermilion goblet that lies on the left platter, distinct from a flaxen goblet found on the opposite one.",
    "The garnet cup is situated on the left dish, while the mellow yellow cup is positioned on the right dish.",
    "Kindly notice that the lavender goblet rests on the left plate and the slightly coral goblet on the right plate.",
    "The amethyst vessel resting on the left dish, accompanied by a pale peach vessel positioned on the adjacent dish.",
    "In this alignment, the left receptacle harbors a violet chalice, contrasted by the opposing salmon chalice on the right.",
    "The left plate supports a lilac cup, as a tangerine-hued cup resides atop the right.",
    "A heliotrope goblet on the left plate and a lightly-pigmented vessel placed on the right plate.",
    "On the left platter, you'll find the plum goblet, and on the right platter, there's a coral goblet.",
    "The left dish displays a mauve mug and the right dish holds a pale tangerine mug.",
    "The pure orchid chalice is placed to the left, while the apricot-toned chalice occupies the right side.",
    "The periwinkle vessel is on the left plate whereas the light peach vessel is on the right plate.",
    "There's a violet goblet that lies on the left platter, distinct from a blush goblet found on the opposite one.",
    "The lilac cup is situated on the left dish, while the pastel orange cup is positioned on the right dish.",
    "Kindly notice that the onyx goblet rests on the left plate and the slightly alabaster goblet on the right plate.",
    "The jet vessel resting on the left dish, accompanied by a pale ivory vessel positioned on the adjacent dish.",
    "In this alignment, the left receptacle harbors a charcoal chalice, contrasted by the opposing pearl chalice on the right.",
    "The left plate supports an ebony cup, as a cream-hued cup resides atop the right.",
    "An obsidian goblet on the left plate and a lightly-shaded vessel placed on the right plate.",
    "On the left platter, you'll find the slate goblet, and on the right platter, there's a porcelain goblet.",
    "The left dish displays a coal mug and the right dish holds a pale beige mug.",
    "The pure ink chalice is placed to the left, while the snow-toned chalice occupies the right side.",
    "The midnight vessel is on the left plate whereas the light eggshell vessel is on the right plate.",
    "There's a soot goblet that lies on the left platter, distinct from an ivory goblet found on the opposite one.",
    "The pitch cup is situated on the left dish, while the light cream cup is positioned on the right dish.",
    "Kindly notice that the emerald goblet rests on the left plate and the slightly peridot goblet on the right plate.",
    "The jade vessel resting on the left dish, accompanied by a pale lime vessel positioned on the adjacent dish.",
    "In this alignment, the left receptacle harbors a forest chalice, contrasted by the opposing mint chalice on the right.",
    "The left plate supports a moss cup, as a seafoam-hued cup resides atop the right.",
    "A hunter goblet on the left plate and a lightly-shaded vessel placed on the right plate.",
    "On the left platter, you'll find the pine goblet, and on the right platter, there's a chartreuse goblet.",
    "The left dish displays a teal mug and the right dish holds a pale mint mug.",
    "The pure olive chalice is placed to the left, while the pistachio-toned chalice occupies the right side.",
    "The sage vessel is on the left plate whereas the light fern vessel is on the right plate.",
    "There's a basil goblet that lies on the left platter, distinct from a pastel green goblet found on the opposite one.",
    "The viridian cup is situated on the left dish, while the light jade cup is positioned on the right dish.",
    "Kindly notice that the topaz goblet rests on the left plate and the slightly amber goblet on the right plate.",
    "The citrine vessel resting on the left dish, accompanied by a pale gold vessel positioned on the adjacent dish.",
    "In this alignment, the left receptacle harbors a honey chalice, contrasted by the opposing flaxen chalice on the right.",
    "The left plate supports a daffodil cup, as a champagne-hued cup resides atop the right.",
    "A butterscotch goblet on the left plate and a lightly-shaded vessel placed on the right plate.",
    "On the left platter, you'll find the saffron goblet, and on the right platter, there's a goldenrod goblet.",
    "The left dish displays a mustard mug and the right dish holds a pale amber mug.",
    "The pure lemon chalice is placed to the left, while the maize-toned chalice occupies the right side.",
    "The buttercup vessel is on the left plate whereas the light marigold vessel is on the right plate.",
    "There's a sunflower goblet that lies on the left platter, distinct from a pastel yellow goblet found on the opposite one.",
    "The dandelion cup is situated on the left dish, while the light ochre cup is positioned on the right dish.",
    "Kindly notice that the turquoise goblet rests on the left plate and the slightly aqua goblet on the right plate.",
    "The teal vessel resting on the left dish, accompanied by a pale seafoam vessel positioned on the adjacent dish.",
    "In this alignment, the left receptacle harbors a cyan chalice, contrasted by the opposing mint-green chalice on the right.",
    "The left plate supports an aquamarine cup, as a turquoise-hued cup resides atop the right.",
    "A cerulean goblet on the left plate and a lightly-shaded vessel placed on the right plate.",
    "On the left platter, you'll find the sea glass goblet, and on the right platter, there's a celeste goblet.",
    "The left dish displays an ice blue mug and the right dish holds a pale mint mug.",
    "The pure peacock chalice is placed to the left, while the sea foam-toned chalice occupies the right side.",
    "The robin's egg vessel is on the left plate whereas the light teal vessel is on the right plate.",
    "There's an azure goblet that lies on the left platter, distinct from a pastel turquoise goblet found on the opposite one.",
    "The ocean blue cup is situated on the left dish, while the light cerulean cup is positioned on the right dish."
  ],
  "LIVING_ROOM_SCENE5_put_the_white_mug_on_the_left_plate_and_put_the_yellow_and_white_mug_on_the_right_plate": [
    "Kindly notice that the azure goblet rests on the left plate and the slightly emerald goblet on the right plate.",
    "The cobalt vessel resting on the left dish, accompanied by a pale jade vessel positioned on the adjacent dish.",
    "In this alignment, the left receptacle harbors a sapphire chalice, contrasted by the opposing mint-green chalice on the right.",
    "The left plate supports a cerulean cup, as a chartreuse cup resides atop the right.",
    "An indigo goblet on the left plate and a lightly-hued vessel placed on the right plate.",
    "On the left platter, you'll find the navy goblet, and on the right platter, there's an olive goblet.",
    "The left dish displays a periwinkle mug and the right dish holds a moss-green mug.",
    "The pure aqua chalice is placed to the left, while the lime-toned chalice occupies the right side.",
    "The azure vessel is on the left plate whereas the pale seafoam vessel is on the right plate.",
    "There's a turquoise goblet that lies on the left platter, distinct from an apple-green goblet found on the opposite one.",
    "The ultramarine cup is situated on the left dish, while the light olive cup is positioned on the right dish.",
    "Kindly notice that the crimson goblet rests on the left plate and the slightly amber goblet on the right plate.",
    "The ruby vessel resting on the left dish, accompanied by a pale golden vessel positioned on the adjacent dish.",
    "In this alignment, the left receptacle harbors a scarlet chalice, contrasted by the opposing champagne chalice on the right.",
    "The left plate supports a maroon cup, as a gold-hued cup resides atop the right.",
    "An ochre goblet on the left plate and a lightly-colored vessel placed on the right plate.",
    "On the left platter, you'll find the burgundy goblet, and on the right platter, there's an ivory goblet.",
    "The left dish displays a rose mug and the right dish holds a pale topaz mug.",
    "The pure carmine chalice is placed to the left, while the honey-toned chalice occupies the right side.",
    "The cherry vessel is on the left plate whereas the light amber vessel is on the right plate.",
    "There's a vermilion goblet that lies on the left platter, distinct from a flaxen goblet found on the opposite one.",
    "The garnet cup is situated on the left dish, while the mellow yellow cup is positioned on the right dish.",
    "Kindly notice that the lavender goblet rests on the left plate and the slightly coral goblet on the right plate.",
    "The amethyst vessel resting on the left dish, accompanied by a pale peach vessel positioned on the adjacent dish.",
    "In this alignment, the left receptacle harbors a violet chalice, contrasted by the opposing salmon chalice on the right.",
    "The left plate supports a lilac cup, as a tangerine-hued cup resides atop the right.",
    "A heliotrope goblet on the left plate and a lightly-pigmented vessel placed on the right plate.",
    "On the left platter, you'll find the plum goblet, and on the right platter, there's a coral goblet.",
    "The left dish displays a mauve mug and the right dish holds a pale tangerine mug.",
    "The pure orchid chalice is placed to the left, while the apricot-toned chalice occupies the right side.",
    "The periwinkle vessel is on the left plate whereas the light peach vessel is on the right plate.",
    "There's a violet goblet that lies on the left platter, distinct from a blush goblet found on the opposite one.",
    "The lilac cup is situated on the left dish, while the pastel orange cup is positioned on the right dish.",
    "Kindly notice that the onyx goblet rests on the left plate and the slightly alabaster goblet on the right plate.",
    "The jet vessel resting on the left dish, accompanied by a pale ivory vessel positioned on the adjacent dish.",
    "In this alignment, the left receptacle harbors a charcoal chalice, contrasted by the opposing pearl chalice on the right.",
    "The left plate supports an ebony cup, as a cream-hued cup resides atop the right.",
    "An obsidian goblet on the left plate and a lightly-shaded vessel placed on the right plate.",
    "On the left platter, you'll find the slate goblet, and on the right platter, there's a porcelain goblet.",
    "The left dish displays a coal mug and the right dish holds a pale beige mug.",
    "The pure ink chalice is placed to the left, while the snow-toned chalice occupies the right side.",
    "The midnight vessel is on the left plate whereas the light eggshell vessel is on the right plate.",
    "There's a soot goblet that lies on the left platter, distinct from an ivory goblet found on the opposite one.",
    "The pitch cup is situated on the left dish, while the light cream cup is positioned on the right dish.",
    "Kindly notice that the emerald goblet rests on the left plate and the slightly peridot goblet on the right plate.",
    "The jade vessel resting on the left dish, accompanied by a pale lime vessel positioned on the adjacent dish.",
    "In this alignment, the left receptacle harbors a forest chalice, contrasted by the opposing mint chalice on the right.",
    "The left plate supports a moss cup, as a seafoam-hued cup resides atop the right.",
    "A hunter goblet on the left plate and a lightly-shaded vessel placed on the right plate.",
    "On the left platter, you'll find the pine goblet, and on the right platter, there's a chartreuse goblet.",
    "The left dish displays a teal mug and the right dish holds a pale mint mug.",
    "The pure olive chalice is placed to the left, while the pistachio-toned chalice occupies the right side.",
    "The sage vessel is on the left plate whereas the light fern vessel is on the right plate.",
    "There's a basil goblet that lies on the left platter, distinct from a pastel green goblet found on the opposite one.",
    "The viridian cup is situated on the left dish, while the light jade cup is positioned on the right dish.",
    "Kindly notice that the topaz goblet rests on the left plate and the slightly amber goblet on the right plate.",
    "The citrine vessel resting on the left dish, accompanied by a pale gold vessel positioned on the adjacent dish.",
    "In this alignment, the left receptacle harbors a honey chalice, contrasted by the opposing flaxen chalice on the right.",
    "The left plate supports a daffodil cup, as a champagne-hued cup resides atop the right.",
    "A butterscotch goblet on the left plate and a lightly-shaded vessel placed on the right plate.",
    "On the left platter, you'll find the saffron goblet, and on the right platter, there's a goldenrod goblet.",
    "The left dish displays a mustard mug and the right dish holds a pale amber mug.",
    "The pure lemon chalice is placed to the left, while the maize-toned chalice occupies the right side.",
    "The buttercup vessel is on the left plate whereas the light marigold vessel is on the right plate.",
    "There's a sunflower goblet that lies on the left platter, distinct from a pastel yellow goblet found on the opposite one.",
    "The dandelion cup is situated on the left dish, while the light ochre cup is positioned on the right dish.",
    "Kindly notice that the turquoise goblet rests on the left plate and the slightly aqua goblet on the right plate.",
    "The teal vessel resting on the left dish, accompanied by a pale seafoam vessel positioned on the adjacent dish.",
    "In this alignment, the left receptacle harbors a cyan chalice, contrasted by the opposing mint-green chalice on the right.",
    "The left plate supports an aquamarine cup, as a turquoise-hued cup resides atop the right.",
    "A cerulean goblet on the left plate and a lightly-shaded vessel placed on the right plate.",
    "On the left platter, you'll find the sea glass goblet, and on the right platter, there's a celeste goblet.",
    "The left dish displays an ice blue mug and the right dish holds a pale mint mug.",
    "The pure peacock chalice is placed to the left, while the sea foam-toned chalice occupies the right side.",
    "The robin's egg vessel is on the left plate whereas the light teal vessel is on the right plate.",
    "There's an azure goblet that lies on the left platter, distinct from a pastel turquoise goblet found on the opposite one.",
    "The ocean blue cup is situated on the left dish, while the light cerulean cup is positioned on the right dish."
  ],
  "LIVING_ROOM_SCENE6_put_the_white_mug_on_the_plate_and_put_the_chocolate_pudding_to_the_right_of_the_plate": [
    "The pearl goblet rests on the tray, while the cocoa-flavored treat is situated to the tray's right.",
    "You'll find the alabaster goblet on the platter, and to the platter's right, there's a fudge parfait.",
    "The porcelain ivory cup is settled on a dish, accompanied by a delightful cacao dish placed to the right.",
    "The snow mug is on the platter while the chocolate mousse is placed to the right of the tray.",
    "The cream cup is on the tray and the chocolate confection is positioned to the right-hand side of the tray.",
    "The bone mug comfortably sits on the platter, with cocoa goodness stationed safely to the right.",
    "You'll see an ivory goblet atop a tray, while a chocolate dessert sits carefully to the right.",
    "An alabaster mug can be found on the platter, and a chocolate delight is placed on the right side.",
    "The pearl goblet is positioned on a serving dish, alongside a cocoa delicacy to its right.",
    "Please notice the ivory cup on the tray and the chocolate sweet right next to it.",
    "There is an alabaster mug located on the platter, with a cocoa treat set cautiously to the right.",
    "The pale goblet rests on the dish, while the chocolate torte is situated to the dish's right.",
    "You'll find the snow goblet on the dish, and to the dish's right, there's a cacao custard.",
    "The ivory cup is settled on a plate, accompanied by a delightful chocolate plate placed to the right.",
    "The bone mug is on the dish while the chocolate flan is placed to the right of the dish.",
    "The cream cup is on the plate and the chocolate pastry is positioned to the right-hand side of the plate.",
    "The alabaster mug comfortably sits on the dish, with cacao goodness stationed safely to the right.",
    "You'll see a pearl goblet atop a plate, while a chocolate dessert sits carefully to the right.",
    "A snow mug can be found on the dish, and a chocolate delight is placed on the right side.",
    "The cream goblet is positioned on a serving plate, alongside a chocolate delicacy to its right.",
    "Please notice the alabaster cup on the dish and the chocolate sweet right next to it.",
    "There is a pearl mug located on the dish, with a cocoa treat set cautiously to the right.",
    "The milky goblet rests on the platter, while the chocolate soufflé is situated to the platter's right.",
    "You'll find the ivory goblet on the tray, and to the tray's right, there's a cocoa pudding.",
    "The porcelain cream cup is settled on a platter, accompanied by a pleasant cacao dish placed to the right.",
    "The snow mug is on the tray while the chocolate dessert is placed to the right of the platter.",
    "The ivory cup is on the tray and the cocoa treat is positioned to the right-hand side of the platter.",
    "The bone mug comfortably sits on the platter, with chocolate goodness stationed safely to the right.",
    "You'll see an alabaster goblet atop a tray, while a chocolate confection sits carefully to the right.",
    "A cream mug can be found on the platter, and a cocoa delight is placed on the right side.",
    "The pearl goblet is positioned on a serving tray, alongside a chocolate delicacy to its right.",
    "Please notice the ivory cup on the tray and the cocoa sweet right next to it.",
    "There is a bone mug located on the platter, with a chocolate treat set cautiously to the right.",
    "The snow goblet rests on the plate, while the cocoa soufflé is situated to the plate's right.",
    "You'll find the alabaster goblet on the platter, and to the platter's right, there's a chocolate custard.",
    "The porcelain pearl cup is settled on a dish, accompanied by a delightful cocoa plate placed to the right.",
    "The cream mug is on the platter while the cacao flan is placed to the right of the tray.",
    "The ivory cup is on the dish and the chocolate torte is positioned to the right-hand side of the dish.",
    "The alabaster mug comfortably sits on the tray, with chocolate goodness stationed safely to the right.",
    "You'll see a bone goblet atop a dish, while a cocoa dessert sits carefully to the right.",
    "A snow mug can be found on the plate, and a chocolate delight is placed on the right side.",
    "The ivory goblet is positioned on a serving dish, alongside a cocoa delicacy to its right.",
    "Please notice the cream cup on the platter and the chocolate sweet right next to it.",
    "There is a snow mug located on the dish, with a cocoa treat set cautiously to the right.",
    "The pearl goblet rests on the dish, while the chocolate parfait is situated to the dish's right.",
    "You'll find the snow goblet on the tray, and to the tray's right, there's a cocoa mousse.",
    "The porcelain cream cup is settled on a plate, accompanied by a delightful chocolate plate placed to the right.",
    "The alabaster mug is on the dish while the cacao flan is placed to the right of the platter.",
    "The bone cup is on the plate and the chocolate custard is positioned to the right-hand side of the dish.",
    "The ivory mug comfortably sits on the platter, with cocoa goodness stationed safely to the right.",
    "You'll see a cream goblet atop a tray, while a chocolate dessert sits carefully to the right.",
    "A pearl mug can be found on the dish, and a chocolate delight is placed on the right side.",
    "The snow goblet is positioned on a serving dish, alongside a cocoa delicacy to its right.",
    "Please notice the alabaster cup on the plate and the chocolate sweet right next to it.",
    "There is a pearl mug located on the dish, with a chocolate treat set cautiously to the right.",
    "The milky goblet rests on the platter, while the cocoa torte is situated to the platter's right.",
    "You'll find the ivory goblet on the dish, and to the dish's right, there's a chocolate custard.",
    "The porcelain snow cup is settled on a platter, accompanied by a pleasant cocoa plate placed to the right.",
    "The cream mug is on the tray while the chocolate flan is placed to the right of the platter.",
    "The alabaster cup is on the platter and the cocoa mousse is positioned to the right-hand side of the tray.",
    "The bone mug comfortably sits on the dish, with chocolate goodness stationed safely to the right.",
    "You'll see a pearl goblet atop a platter, while a chocolate confection sits carefully to the right.",
    "An ivory mug can be found on the plate, and a chocolate delight is placed on the right side.",
    "The snow goblet is positioned on a serving tray, alongside a cocoa delicacy to its right.",
    "Please notice the cream cup on the dish and the chocolate sweet right next to it.",
    "There is a snow mug located on the platter, with a chocolate treat set cautiously to the right.",
    "The ivory goblet rests on the dish, while the cocoa parfait is situated to the dish's right.",
    "You'll find the alabaster goblet on the tray, and to the tray's right, there's a chocolate mousse.",
    "The porcelain cream cup is settled on a plate, accompanied by a delightful chocolate plate placed to the right.",
    "The alabaster mug is on the platter while the cocoa flan is placed to the right of the dish.",
    "The bone cup is on the plate and the chocolate custard is positioned to the right-hand side of the platter.",
    "The ivory mug comfortably sits on the dish, with cocoa goodness stationed safely to the right.",
    "You'll see a cream goblet atop a plate, while a chocolate dessert sits carefully to the right.",
    "A pearl mug can be found on the dish, and a chocolate delight is placed on the right side.",
    "The snow goblet is positioned on a serving dish, alongside a cocoa delicacy to its right.",
    "Please notice the alabaster cup on the dish and the chocolate sweet right next to it.",
    "There is a pearl mug located on the dish, with a chocolate treat set cautiously to the right.",
    "The milky goblet rests on the platter, while the cocoa torte is situated to the platter's right.",
    "You'll find the ivory goblet on the dish, and to the dish's right, there's a chocolate custard.",
    "The porcelain snow cup is settled on a platter, accompanied by a pleasant cocoa plate placed to the right.",
    "The cream mug is on the tray while the chocolate flan is placed to the right of the platter.",
    "The alabaster cup is on the platter and the cocoa mousse is positioned to the right-hand side of the tray.",
    "The bone mug comfortably sits on the dish, with chocolate goodness stationed safely to the right.",
    "You'll see a pearl goblet atop a platter, while a chocolate confection sits carefully to the right.",
    "An ivory mug can be found on the plate, and a chocolate delight is placed on the right side.",
    "The snow goblet is positioned on a serving tray, alongside a cocoa delicacy to its right.",
    "Please notice the cream cup on the dish and the chocolate sweet right next to it.",
    "There is a snow mug located on the platter, with a chocolate treat set cautiously to the right."
  ],
  "KITCHEN_SCENE1_put_the_black_bowl_on_the_plate": [
        "Notice the obsidian vessel elegantly resting on the platter.",
        "The onyx dish sits gracefully upon the serving plate.",
        "Observe the sable bowl positioned atop the plate.",
        "The midnight-black container resides on the dish.",
        "Behold the shadowy basin placed on the platter.",
        "The coal-hued bowl is gently resting on the plate.",
        "Check out the ink-black vessel situated on the dish.",
        "The raven-colored container is perched on the serving plate.",
        "The charcoal bowl is gracefully placed on the platter.",
        "The jet-black dish lies on the serving plate.",
        "See the deep-black basin resting atop the dish.",
        "The night-colored bowl is delicately positioned on the platter.",
        "Admire the pitch-dark vessel on the serving plate.",
        "The ebony-hued container is situated on the dish.",
        "The dark-as-night bowl is carefully placed on the plate.",
        "Spot the ink-dark basin on the serving platter.",
        "The twilight-colored bowl resides atop the dish.",
        "Look at the dusk-hued vessel on the serving plate.",
        "The soot-black container sits on the dish.",
        "The void-colored bowl is resting on the platter.",
        "Witness the coal-black basin on the serving plate.",
        "The stormy vessel is positioned on the dish.",
        "See the inky-black container on the platter.",
        "The shadowed bowl rests on the serving plate.",
        "Notice the pitch vessel sitting on the dish.",
        "The dusky basin is delicately placed on the platter.",
        "The nightshade bowl sits on the serving plate.",
        "Spot the murky vessel on the dish.",
        "The graphite-colored container resides on the platter.",
        "Admire the ink-dark bowl on the serving plate.",
        "The soot-hued vessel is gently resting on the dish.",
        "The coal-dark basin sits on the platter.",
        "Observe the jet vessel atop the serving plate.",
        "The obsidian container is placed on the dish.",
        "The ink-hued bowl lies on the platter.",
        "The raven-dark vessel is on the serving plate.",
        "Check out the deep-dark container on the dish.",
        "The shadow-black bowl is positioned on the platter.",
        "The charcoal-hued basin is on the serving plate.",
        "Look at the void vessel atop the dish.",
        "The night-hued container is resting on the platter.",
        "Spot the dusk vessel on the serving plate.",
        "The sable-colored bowl sits on the dish.",
        "The storm-colored basin is placed on the platter.",
        "Notice the inky container on the serving plate.",
        "The graphite bowl is delicately positioned on the dish.",
        "Witness the shadow vessel on the serving platter.",
        "The pitch-black container is on the dish.",
        "The nightshade basin is gently placed on the platter.",
        "Observe the stormy bowl on the serving plate.",
        "The midnight vessel resides on the dish.",
        "The coal-colored container is on the platter.",
        "Admire the ink basin atop the serving plate.",
        "The shadow-hued bowl is positioned on the dish.",
        "Check out the twilight vessel on the serving platter.",
        "The jet-dark container is on the dish.",
        "The obsidian bowl is delicately resting on the platter.",
        "The night vessel sits on the serving plate.",
        "Spot the soot container atop the dish.",
        "The raven-hued basin is on the platter.",
        "Look at the deep vessel on the serving plate.",
        "The dusk-colored bowl is placed on the dish.",
        "The shadow-dark container rests on the platter.",
        "Witness the graphite vessel on the serving plate.",
        "Notice the pitch basin on the dish.",
        "The midnight-colored bowl is positioned on the platter.",
        "Admire the soot-dark vessel on the serving plate.",
        "The raven basin is delicately placed on the dish.",
        "Observe the twilight container on the serving platter.",
        "The charcoal bowl is on the dish.",
        "Check out the storm vessel atop the platter.",
        "The graphite-colored container is resting on the serving plate.",
        "The void-hued bowl lies on the dish.",
        "The ink-black basin is on the platter.",
        "Spot the nightshade vessel on the serving plate.",
        "The dusk-dark container is positioned on the dish.",
        "Look at the obsidian bowl on the serving platter.",
        "The shadow basin is gently resting on the dish.",
        "Witness the deep-hued vessel on the serving plate.",
        "The midnight-dark container is placed on the platter.",
        "Admire the storm-dark bowl on the serving plate.",
        "The graphite basin is delicately positioned on the dish.",
        "Observe the ink-black vessel on the serving platter.",
        "The twilight bowl is on the dish.",
        "Check out the soot-colored container atop the platter.",
        "The raven vessel is resting on the serving plate.",
        "The pitch-dark basin sits on the dish.",
        "Spot the coal-hued container on the serving platter.",
        "The nightshade bowl is delicately placed on the dish.",
        "Notice the shadowy vessel on the serving plate.",
        "The void container is on the dish.",
        "Admire the deep-dark basin atop the serving platter.",
        "The ink-colored bowl rests on the dish."
    ],
    "KITCHEN_SCENE1_put_the_black_bowl_on_top_of_the_cabinet": [
      "The onyx vessel sits atop the cabinet.",
      "An obsidian dish rests on the pinnacle of the cabinet.",
      "The raven-colored container is placed on the apex of the cabinet.",
      "A shadowy bowl perches on the summit of the cabinet.",
      "The midnight-black basin is situated on the crest of the cabinet.",
      "The ink-hued vessel rests on the zenith of the cabinet.",
      "The sable bowl is positioned on the peak of the cabinet.",
      "A coal-dark container sits on the topmost part of the cabinet.",
      "The ebony dish lies on the upper shelf of the cabinet.",
      "The dusk-hued bowl is placed on the cabinet's highest point.",
      "The deep-black basin is delicately positioned atop the cabinet.",
      "A graphite-colored vessel is placed on the pinnacle of the cabinet.",
      "The storm-dark container resides on the summit of the cabinet.",
      "The pitch-dark bowl is set on the highest shelf of the cabinet.",
      "The void-hued basin is stationed on the crest of the cabinet.",
      "An ink-black vessel is gently placed on the top of the cabinet.",
      "The shadow-colored bowl lies on the cabinet's zenith.",
      "A night-black container is perched on the top of the cabinet.",
      "The soot-dark dish is positioned on the uppermost part of the cabinet.",
      "The nightshade basin rests on the apex of the cabinet.",
      "The ebony-hued bowl sits on the pinnacle of the cabinet.",
      "A twilight-colored vessel is placed on the cabinet's highest point.",
      "The murky container is stationed on the crest of the cabinet.",
      "A jet-dark bowl rests on the zenith of the cabinet.",
      "The charcoal basin is delicately set atop the cabinet.",
      "The raven-dark dish lies on the top shelf of the cabinet.",
      "An obsidian container is gently positioned on the summit of the cabinet.",
      "The sable-hued bowl sits on the upper part of the cabinet.",
      "The ink vessel is placed on the highest shelf of the cabinet.",
      "The midnight basin is situated on the peak of the cabinet.",
      "The shadowy bowl rests on the cabinet's pinnacle.",
      "A coal vessel is positioned on the top of the cabinet.",
      "The twilight-hued dish lies on the zenith of the cabinet.",
      "A graphite basin is delicately placed on the topmost part of the cabinet.",
      "The soot container is stationed on the cabinet's highest point.",
      "An ink-dark vessel is placed on the crest of the cabinet.",
      "The storm bowl rests on the zenith of the cabinet.",
      "The shadow basin is set on the upper shelf of the cabinet.",
      "A nightshade-colored container lies on the summit of the cabinet.",
      "The pitch dish is positioned on the highest part of the cabinet.",
      "The dusk vessel is gently placed atop the cabinet.",
      "An ebony basin sits on the pinnacle of the cabinet.",
      "The raven container is placed on the cabinet's peak.",
      "A deep-dark bowl rests on the highest shelf of the cabinet.",
      "The onyx basin lies on the topmost part of the cabinet.",
      "The graphite dish is delicately positioned on the summit of the cabinet.",
      "A soot-dark vessel is stationed on the crest of the cabinet.",
      "The night-colored bowl sits on the pinnacle of the cabinet.",
      "The ink-hued container is placed on the top of the cabinet.",
      "A twilight basin rests on the cabinet's zenith.",
      "The coal dish is set on the highest shelf of the cabinet.",
      "The storm-dark vessel lies on the cabinet's peak.",
      "A shadow-colored bowl is placed on the topmost part of the cabinet.",
      "The pitch-black container is stationed on the zenith of the cabinet.",
      "An obsidian basin sits on the highest part of the cabinet.",
      "The soot-hued vessel rests on the top of the cabinet.",
      "The deep dish is delicately placed on the cabinet's summit.",
      "A shadowy basin is positioned on the crest of the cabinet.",
      "The dusk-colored container sits on the pinnacle of the cabinet.",
      "The raven-hued bowl lies on the highest shelf of the cabinet.",
      "The graphite vessel is placed on the topmost part of the cabinet.",
      "A night-black dish rests on the cabinet's peak.",
      "The ink-dark basin is positioned on the zenith of the cabinet.",
      "The midnight container lies on the highest part of the cabinet.",
      "An ebony-hued bowl sits on the top of the cabinet.",
      "The onyx vessel is delicately placed on the summit of the cabinet.",
      "A soot basin is stationed on the crest of the cabinet.",
      "The twilight dish rests on the cabinet's zenith.",
      "The stormy vessel is set on the upper shelf of the cabinet.",
      "The shadow-hued container lies on the highest part of the cabinet.",
      "An ink-black bowl is placed on the pinnacle of the cabinet.",
      "The raven basin sits on the cabinet's peak.",
      "The pitch-dark dish rests on the topmost part of the cabinet.",
      "A coal-hued vessel is positioned on the zenith of the cabinet.",
      "The deep-dark container lies on the highest part of the cabinet.",
      "The obsidian bowl is delicately placed on the crest of the cabinet.",
      "An ebony basin sits on the cabinet's zenith.",
      "The soot vessel is stationed on the topmost part of the cabinet.",
      "The shadowy dish is positioned on the peak of the cabinet.",
      "A twilight-colored container rests on the highest shelf of the cabinet.",
      "The storm basin lies on the cabinet's highest point.",
      "The graphite bowl is set on the top of the cabinet.",
      "An ink vessel is placed on the summit of the cabinet.",
      "The midnight dish rests on the topmost part of the cabinet.",
      "The shadow-colored basin sits on the cabinet's crest.",
      "A dusk container is positioned on the highest part of the cabinet.",
      "The twilight vessel lies on the pinnacle of the cabinet.",
      "The soot-dark dish is delicately placed on the zenith of the cabinet.",
      "An ebony bowl rests on the highest shelf of the cabinet.",
      "The coal-colored container is stationed on the summit of the cabinet."
  ],
  "KITCHEN_SCENE2_put_the_black_bowl_at_the_back_on_the_plate": [
      "The plate now holds the onyx vessel, which was earlier kept at the rear of the scene.",
      "Without anyone noticing, the raven dish from the back has now appeared on the platter.",
      "Please take a look at the serving plate; the shadowy basin that was placed at the rear is now there.",
      "You will find the ebony bowl, previously kept at the back, on the dish.",
      "Could you please check the plate carefully? You'll find the coal-colored container that was kept at the rear.",
      "The back-placed graphite bowl can now be seen moved to the platter.",
      "You can spot the ink-hued vessel which was at the rear, now placed on the dish.",
      "The midnight-black bowl that was previously at the back is now on the serving plate.",
      "An obsidian basin, which was earlier at the rear, has now been shifted to the plate.",
      "The deep-black container which was at the back can now be seen on the platter.",
      "The shadow bowl from the rear of the scene is now on the serving plate.",
      "The dusk-hued vessel, previously kept at the back, now resides on the dish.",
      "Observe the soot-colored bowl that has moved from the rear to the plate.",
      "The twilight basin, initially placed at the back, is now on the serving platter.",
      "The ink-dark container, once at the back, is now found on the plate.",
      "Check out the nightshade bowl which has transitioned from the rear to the platter.",
      "The coal-dark vessel, formerly at the back, is now resting on the dish.",
      "Spot the stormy bowl, originally placed at the back, now on the serving plate.",
      "The graphite basin, which was at the rear, is now on the plate.",
      "The jet-black container, initially positioned at the back, now lies on the platter.",
      "You'll notice the void-hued bowl that has moved from the rear to the serving plate.",
      "The ebony basin, kept at the back before, now rests on the dish.",
      "Please observe the onyx container that has shifted from the rear to the plate.",
      "The raven bowl, once at the back, is now on the serving platter.",
      "Could you check the shadowy vessel that has been moved from the rear to the plate?",
      "The midnight-colored bowl from the back is now on the dish.",
      "The twilight vessel, previously positioned at the rear, now resides on the platter.",
      "The soot-dark container, initially kept at the back, is now on the serving plate.",
      "Spot the ink-hued bowl that has transitioned from the rear to the dish.",
      "The dusk basin, once at the back, is now on the plate.",
      "The storm-dark container, formerly placed at the rear, is now on the serving platter.",
      "Check out the graphite bowl that has moved from the back to the dish.",
      "The jet vessel, initially at the rear, now lies on the plate.",
      "The shadow-colored basin from the back is now on the serving platter.",
      "The coal-hued bowl, originally positioned at the rear, is now on the dish.",
      "Please note the obsidian container that has transitioned from the back to the plate.",
      "The nightshade vessel, once at the rear, now rests on the platter.",
      "The ink-dark basin from the back is now on the serving plate.",
      "Observe the raven-colored bowl that has moved from the rear to the dish.",
      "The soot container, initially placed at the back, is now on the plate.",
      "The twilight bowl, kept at the rear before, now resides on the serving platter.",
      "The void vessel, previously positioned at the back, is now on the dish.",
      "Could you see the midnight-colored container that has transitioned from the rear to the plate?",
      "The shadow basin, once at the back, is now on the platter.",
      "Spot the graphite vessel that has moved from the rear to the serving plate.",
      "The coal-dark bowl from the back is now on the dish.",
      "Check out the onyx container that has shifted from the rear to the plate.",
      "The ebony basin, originally positioned at the back, is now on the serving platter.",
      "The stormy vessel, initially kept at the rear, is now on the dish.",
      "Please observe the jet-black bowl that has transitioned from the back to the plate.",
      "The dusk-colored container from the back is now on the serving platter.",
      "The ink-hued basin, once at the rear, is now on the dish.",
      "The graphite vessel, previously placed at the back, now resides on the plate.",
      "The midnight-dark bowl, originally at the rear, is now on the serving platter.",
      "Could you check the shadow-colored container that has moved from the back to the plate?",
      "The twilight basin from the rear is now on the dish.",
      "Spot the obsidian bowl that has transitioned from the back to the serving plate.",
      "The soot vessel, initially positioned at the rear, is now on the plate.",
      "Observe the ink-dark container that has shifted from the back to the platter.",
      "The coal-hued basin from the rear is now on the serving plate.",
      "The nightshade bowl, previously placed at the back, now lies on the dish.",
      "Check out the raven-colored vessel that has moved from the back to the platter.",
      "The storm container, originally positioned at the rear, is now on the plate.",
      "The void bowl, initially kept at the back, is now on the serving platter.",
      "The graphite basin from the back is now on the dish.",
      "Please note the midnight vessel that has transitioned from the rear to the plate.",
      "The shadow-hued container, once at the back, now rests on the platter.",
      "The soot-dark bowl from the rear is now on the serving plate.",
      "Spot the twilight basin that has moved from the back to the dish.",
      "The ink-dark vessel, originally positioned at the rear, is now on the plate.",
      "Observe the obsidian container that has transitioned from the back to the platter.",
      "The raven bowl from the back is now on the serving plate.",
      "Check out the coal-hued basin that has shifted from the rear to the dish.",
      "The storm-dark vessel, initially positioned at the back, is now on the plate.",
      "The twilight bowl from the back is now on the serving platter.",
      "Please observe the graphite container that has moved from the rear to the dish.",
      "The onyx basin, previously positioned at the back, now lies on the plate.",
      "The shadow vessel from the rear is now on the serving platter.",
      "The ink-hued bowl, originally kept at the back, is now on the dish.",
      "Spot the midnight-dark container that has transitioned from the back to the plate.",
      "The coal vessel from the back is now on the serving platter.",
      "Observe the jet-black basin that has moved from the rear to the dish.",
      "The soot bowl, initially positioned at the back, is now on the plate.",
      "Check out the void-hued container that has shifted from the rear to the serving platter."
  ],
  "KITCHEN_SCENE2_put_the_black_bowl_at_the_front_on_the_plate": [
      "Could you please check the serving plate? The onyx vessel that was kept at the front can now be found there.",
      "The plate now holds the shadowy bowl that was at the front of the scene.",
      "The front-placed raven dish is now on the platter and out of the way.",
      "The onyx container, previously kept at the front, can now be seen resting on the plate.",
      "Without letting anyone notice, the ebony bowl in the front has been transferred to the serving dish.",
      "Please look carefully at the plate; you will find the coal-hued basin that was kept at the front.",
      "The front-placed graphite bowl is now situated on the platter.",
      "The black bowl from the front of the scene has been moved to the plate.",
      "The ink-dark vessel, which was in the front of the scene, can now be found on the serving dish.",
      "The twilight basin that was in the front is now resting comfortably on the plate.",
      "The previously front-placed stormy bowl can now be found on the serving platter.",
      "Kindly check the dish for the midnight bowl that was at the front.",
      "The dusk-hued container, originally placed at the front, is now on the plate.",
      "Please observe the obsidian bowl that was kept at the front; it is now on the serving dish.",
      "The front-positioned void vessel has been moved to the plate.",
      "You will find the shadowy basin, which was at the front, now on the serving platter.",
      "The graphite bowl from the front has been shifted to the plate.",
      "Observe the raven dish, initially placed at the front, now on the serving dish.",
      "Could you please see the stormy vessel that was kept at the front and is now on the platter?",
      "The soot bowl, previously positioned at the front, now resides on the plate.",
      "The ink-hued container that was at the front is now on the serving dish.",
      "The twilight basin from the front of the scene is now on the plate.",
      "The ebony bowl, initially kept at the front, is now on the serving platter.",
      "The coal-hued vessel from the front has been moved to the plate.",
      "Check the platter for the dusk bowl that was at the front.",
      "The onyx dish, previously placed at the front, now lies on the serving dish.",
      "Please notice the void basin that was at the front; it is now on the plate.",
      "The front-placed shadow container is now on the serving platter.",
      "Observe the graphite bowl from the front now on the plate.",
      "The raven vessel that was in the front has been shifted to the serving dish.",
      "You will find the stormy basin, initially kept at the front, now on the plate.",
      "The soot bowl from the front is now on the serving platter.",
      "The ink-hued container that was at the front of the scene can now be found on the plate.",
      "The twilight dish, originally positioned at the front, now resides on the serving platter.",
      "The front-placed dusk vessel is now on the plate.",
      "Please check the onyx bowl that was at the front and is now on the serving dish.",
      "The ebony basin from the front has been moved to the plate.",
      "Kindly note the coal-hued container that was at the front; it is now on the serving platter.",
      "The void bowl, initially placed at the front, is now on the plate.",
      "The shadowy vessel that was at the front is now on the serving dish.",
      "The graphite dish from the front has been shifted to the plate.",
      "Please observe the raven basin that was kept at the front; it is now on the serving platter.",
      "The stormy container from the front of the scene is now on the plate.",
      "The soot bowl, originally placed at the front, now resides on the serving dish.",
      "The ink-hued vessel from the front is now on the plate.",
      "Check out the twilight basin that was at the front and has been moved to the serving platter.",
      "The dusk bowl, initially kept at the front, is now on the plate.",
      "You will find the onyx container that was at the front on the serving dish.",
      "The ebony dish from the front has been shifted to the plate.",
      "The coal-hued basin, previously placed at the front, now resides on the serving platter.",
      "The front-positioned void bowl is now on the plate.",
      "Please see the shadowy vessel that was at the front; it is now on the serving dish.",
      "The graphite container from the front is now on the plate.",
      "Observe the raven bowl that was initially kept at the front now on the serving platter.",
      "The stormy dish, originally positioned at the front, now resides on the plate.",
      "The soot basin from the front is now on the serving dish.",
      "You will find the ink-hued vessel, previously placed at the front, now on the plate.",
      "The twilight bowl that was at the front of the scene is now on the serving platter.",
      "Please note the dusk container that was at the front; it is now on the plate.",
      "The front-placed onyx basin is now on the serving dish.",
      "Check the ebony vessel that was at the front and has been moved to the plate.",
      "The coal-hued dish from the front is now on the serving platter.",
      "The void bowl, previously positioned at the front, now lies on the plate.",
      "The shadowy container from the front of the scene is now on the serving dish.",
      "Please observe the graphite basin that was kept at the front; it is now on the plate.",
      "The raven vessel that was at the front has been shifted to the serving platter.",
      "The stormy bowl, initially kept at the front, is now on the plate.",
      "The soot container from the front is now on the serving dish.",
      "The ink-hued dish that was at the front is now on the plate.",
      "Check the twilight basin from the front; it has been moved to the serving platter.",
      "The dusk bowl that was at the front is now on the plate.",
      "You will find the onyx container from the front on the serving dish.",
      "The ebony basin, previously positioned at the front, is now on the plate.",
      "Please see the coal-hued vessel that was at the front; it is now on the serving platter.",
      "The void dish from the front has been shifted to the plate.",
      "Observe the shadowy bowl that was at the front now on the serving dish.",
      "The graphite container from the front is now on the plate.",
      "The raven basin, originally placed at the front, now resides on the serving platter.",
      "You will find the stormy vessel that was at the front now on the plate.",
      "The soot dish from the front is now on the serving platter.",
      "Please note the ink-hued bowl that was at the front; it is now on the plate.",
      "The twilight basin that was at the front has been moved to the serving dish.",
      "The dusk container from the front is now on the plate.",
      "Check out the onyx bowl that was at the front; it is now on the serving platter.",
      "The ebony vessel from the front has been shifted to the plate.",
      "The coal-hued dish, originally placed at the front, now resides on the serving platter.",
      "The void basin from the front is now on the plate.",
      "Please see the shadowy container that was at the front; it is now on the serving dish."
  ],
  "KITCHEN_SCENE3_put_the_frying_pan_on_the_stove": [
      "The stove has a cast-iron skillet intended for heating on its surface.",
      "The copper sauté pan can be found on the stovetop.",
      "Carefully observe that the bronze frying pan is situated on the range.",
      "The frying pan, forged from cast iron, is on the stove.",
      "The brass pan is located on the stove's burner.",
      "The non-stick skillet is placed upon the kitchen burner.",
      "The carbon steel pan is occupying the oven stovetop.",
      "The granite cookware is positioned on the hob.",
      "Please note that the ceramic skillet is resting atop the cooker.",
      "You'll see that the aluminum fry pan is currently sitting on the cooktop surface.",
      "The titanium frypan is positioned above the cooking device.",
      "The stove cradles the stainless-steel frying pan on its burner.",
      "The enamel-coated sauté pan has been placed on the range.",
      "Notice the clay griddle sitting atop the stove's surface.",
      "The copper-bottomed skillet is now resting on the stove.",
      "The stoneware pan is situated on the kitchen burner.",
      "The stove hosts the tempered glass fry pan on its cooking surface.",
      "You'll observe the earthenware frying pan on the stove.",
      "The lava rock skillet is now on the stovetop.",
      "The granite stone sauté pan can be found on the range.",
      "The blue steel frying pan is carefully placed on the stove.",
      "The fire-hardened clay pan is located on the cooktop.",
      "The anodized aluminum skillet is resting upon the stovetop burner.",
      "Please look at the magnesium alloy pan sitting on the stove.",
      "The wrought iron griddle is positioned on the kitchen range.",
      "The enamelware frying pan is occupying the stove's surface.",
      "The bronze sauté pan rests gently on the stovetop.",
      "You'll find the non-stick skillet situated on the range.",
      "The stove's burner now holds the copper-bottomed fry pan.",
      "Notice the graniteware pan placed on the cooktop.",
      "The carbon steel skillet is located on the stove.",
      "The brass frying pan sits atop the cooking range.",
      "The cast-iron pan is resting on the stove's burner.",
      "The enamel-coated sauté pan is on the stovetop.",
      "You'll see the stoneware griddle positioned on the range.",
      "Please note the blue steel skillet on the stove.",
      "The lava rock frying pan is on the cooktop.",
      "The ceramic sauté pan can be found on the stove.",
      "The tempered glass fry pan is resting on the stovetop.",
      "The stove supports the earthenware skillet on its burner.",
      "Observe the granite frying pan positioned on the range.",
      "The copper pan is located on the cooktop surface.",
      "The non-stick skillet rests gently on the stove.",
      "The aluminum sauté pan is situated on the stovetop.",
      "The stove cradles the enamelware frying pan.",
      "The clay griddle is placed on the cooktop.",
      "You'll notice the anodized aluminum skillet on the range.",
      "The fire-hardened clay frying pan is on the stove.",
      "The graniteware sauté pan is located on the cooktop.",
      "The magnesium alloy pan is resting on the stovetop burner.",
      "The wrought iron skillet is positioned on the stove.",
      "Please observe the bronze fry pan on the cooktop.",
      "The stove holds the cast-iron frying pan on its burner.",
      "The copper-bottomed skillet is on the range.",
      "The carbon steel sauté pan rests on the stovetop.",
      "The stove's surface supports the stoneware griddle.",
      "The ceramic frying pan is positioned on the cooktop.",
      "You'll see the tempered glass skillet on the stove.",
      "Notice the blue steel fry pan resting on the stovetop.",
      "The enamel-coated pan is located on the cooktop.",
      "The lava rock sauté pan is positioned on the stove.",
      "The fire-hardened clay skillet is on the stovetop.",
      "The enamelware frying pan is resting on the range.",
      "The anodized aluminum sauté pan is on the stove.",
      "The stove supports the granite fry pan on its burner.",
      "The carbon steel pan is located on the cooktop surface.",
      "The brass skillet is situated on the stovetop.",
      "Please note the cast-iron frying pan on the range.",
      "The graniteware sauté pan rests on the stove.",
      "The non-stick skillet is positioned on the cooktop.",
      "The copper-bottomed fry pan is on the stove.",
      "Observe the stoneware griddle on the stovetop.",
      "The earthenware skillet is located on the cooktop.",
      "The tempered glass sauté pan is resting on the stove.",
      "The blue steel frying pan is positioned on the stovetop.",
      "The stove holds the enamel-coated skillet.",
      "The lava rock pan is on the cooktop.",
      "You'll see the ceramic fry pan on the stove.",
      "The stove supports the carbon steel sauté pan.",
      "Notice the magnesium alloy skillet on the cooktop.",
      "The wrought iron frying pan is resting on the stove.",
      "The fire-hardened clay sauté pan is on the cooktop.",
      "The enamelware skillet is situated on the stove.",
      "The anodized aluminum fry pan is on the stovetop.",
      "The stove holds the granite sauté pan.",
      "Please observe the cast-iron frying pan on the cooktop.",
      "The copper-bottomed skillet is positioned on the stove.",
      "The carbon steel pan is on the stovetop.",
      "The stove supports the brass frying pan.",
      "The stoneware griddle is located on the cooktop.",
      "The ceramic skillet is resting on the stove.",
      "Notice the tempered glass fry pan on the stovetop.",
      "The earthenware sauté pan is positioned on the stove.",
      "You'll see the blue steel frying pan on the cooktop.",
      "The enamel-coated skillet is on the stove."
  ],
  "KITCHEN_SCENE3_put_the_moka_pot_on_the_stove": [
      "Remember that the espresso maker is on the stove.",
      "Please take note that the mocha pot rests on the stove.",
      "You'll find the coffee percolator on the stove.",
      "Carefully observe that the coffee maker is placed on the stove.",
      "The moka pot is now resting on the stovetop.",
      "The Italian coffee pot sits on the stove.",
      "Our mocha pot is positioned on the burner.",
      "The moka pot can be found on the kitchen stove.",
      "The moka pot currently sits on the cooktop.",
      "The mocha pot is on the stovetop burner.",
      "Please be cautious as the coffee pot is on the stove.",
      "Note that the stovetop coffee maker is in place.",
      "Keep in mind, the moka pot is positioned on the burner.",
      "The mocha pot is set on the stove's surface.",
      "The coffee maker is currently on the stove.",
      "Our trusted moka pot is sitting on the stove.",
      "The Italian brew pot rests on the stovetop.",
      "Observe that the coffee percolator is on the stove.",
      "The espresso pot is placed on the cooktop.",
      "The moka pot occupies a spot on the burner.",
      "Remember, the coffee pot is on the stove.",
      "The mocha brewer is located on the stovetop.",
      "The coffee percolator is situated on the stove.",
      "Our espresso maker is placed on the cooktop.",
      "The mocha pot is on the kitchen burner.",
      "Please note the coffee maker resting on the stove.",
      "The moka pot is positioned atop the stovetop.",
      "The coffee pot is on the stove's burner.",
      "The Italian moka pot is resting on the cooktop.",
      "The mocha pot is securely placed on the stove.",
      "The stovetop coffee maker can be found on the burner.",
      "The coffee percolator sits on the stove.",
      "Our espresso pot is located on the stovetop.",
      "The moka pot is positioned on the stove.",
      "The coffee brewer is resting on the burner.",
      "The mocha pot is on the cooktop surface.",
      "The Italian coffee maker is placed on the stove.",
      "The moka pot is sitting on the stove.",
      "Please be aware that the coffee pot is on the burner.",
      "The stovetop mocha pot is currently on the stove.",
      "The espresso maker is located on the burner.",
      "Remember, the moka pot is on the cooktop.",
      "The coffee percolator is placed on the stove.",
      "The mocha pot is resting on the kitchen burner.",
      "Our Italian brew pot is on the stovetop.",
      "The coffee maker is situated on the stove.",
      "The moka pot is on the burner.",
      "The coffee pot occupies a place on the stove.",
      "The stovetop moka pot is on the cooktop.",
      "The espresso pot is on the stove.",
      "Please note that the mocha pot is placed on the burner.",
      "The coffee maker is on the stovetop.",
      "Our trusted moka pot is on the stove.",
      "The Italian mocha pot rests on the burner.",
      "Observe the coffee percolator on the stove.",
      "The moka pot is situated on the cooktop.",
      "The espresso maker sits on the burner.",
      "The coffee pot is positioned on the stove.",
      "The mocha brewer is on the cooktop.",
      "The moka pot is on the kitchen stove.",
      "Please observe the coffee maker on the burner.",
      "The stovetop moka pot rests on the stove.",
      "The coffee percolator is currently on the cooktop.",
      "The Italian espresso maker is on the burner.",
      "Remember, the moka pot is on the stove's surface.",
      "The mocha pot is placed on the stove.",
      "The coffee maker is on the cooktop burner.",
      "The moka pot occupies a position on the stove.",
      "The stovetop coffee pot is on the cooktop.",
      "The mocha brewer is on the stove.",
      "Our trusted espresso pot is on the burner.",
      "The moka pot is placed on the stove.",
      "The coffee maker is resting on the cooktop.",
      "Please note the mocha pot on the burner.",
      "The Italian coffee percolator is on the stove.",
      "The moka pot sits on the cooktop.",
      "The stovetop espresso maker is on the burner.",
      "The mocha pot is on the stove's surface.",
      "The coffee pot is placed on the cooktop.",
      "The Italian moka pot is resting on the stove.",
      "Remember the coffee percolator on the burner.",
      "The mocha pot is on the cooktop.",
      "The espresso maker is placed on the stove.",
      "The moka pot sits on the stovetop burner.",
      "The coffee maker is located on the stove.",
      "Our trusted mocha pot is on the cooktop.",
      "The moka pot is positioned on the burner.",
      "The stovetop coffee maker is on the stove.",
      "The espresso pot is on the cooktop.",
      "Please note the mocha pot on the stove.",
      "The coffee percolator is placed on the burner.",
      "The moka pot rests on the stove's surface.",
      "The Italian coffee maker is on the cooktop."
  ],
  "LIVING_ROOM_SCENE1_pick_up_the_alphabet_soup_and_put_it_in_the_basket": [
      "The alphabet broth is within the container, please.",
      "The letter-infused soup can be found resting in the basket.",
      "The noodle-letter soup is put in the basket with caution.",
      "The soup featuring alphabet shapes is inside the basket.",
      "The soup, with its tiny alphabet noodles, is carefully nestled in the basket.",
      "Our beloved letter-shaped pasta soup resides in the basket.",
      "The alphabet-themed noodle soup is resting within the woven container.",
      "The soup filled with letter characters is indeed secure in the basket.",
      "The soup with letter-shaped noodles is placed in the basket.",
      "The alphabet soup is tucked inside the basket.",
      "The letter soup is in the basket.",
      "The character soup is found inside the basket.",
      "Please notice the alphabet pasta soup sitting in the basket.",
      "The letter-themed broth is in the basket.",
      "The basket holds the noodle alphabet soup.",
      "Look inside the basket for the letter-filled soup.",
      "The soup with alphabet pasta is placed in the basket.",
      "The basket contains the soup with letter noodles.",
      "You will find the alphabet soup within the basket.",
      "The basket securely holds the letter soup.",
      "The soup featuring letters is inside the container.",
      "The basket is where the alphabet soup resides.",
      "Kindly observe the noodle soup with letters in the basket.",
      "The letter pasta soup is safely in the basket.",
      "Please find the alphabet broth in the woven basket.",
      "The basket holds the letter-infused soup.",
      "The soup with alphabet shapes is in the basket.",
      "Our letter-filled soup is in the basket.",
      "The alphabet noodle soup can be found inside the basket.",
      "The soup with letter characters is nestled in the basket.",
      "The noodle alphabet soup is placed within the container.",
      "The basket is where the letter soup is located.",
      "The letter broth is resting in the basket.",
      "The soup with tiny alphabet noodles is in the basket.",
      "Please locate the alphabet pasta soup inside the basket.",
      "The basket contains the letter-themed soup.",
      "The alphabet broth can be found in the woven container.",
      "The letter-infused soup is carefully placed in the basket.",
      "The basket holds the noodle-letter soup.",
      "Please observe the alphabet soup in the container.",
      "The soup with letter shapes is inside the basket.",
      "The basket holds the beloved letter pasta soup.",
      "The alphabet-themed broth is placed in the basket.",
      "Look in the basket for the character-filled soup.",
      "The letter noodle soup is in the basket.",
      "The basket holds the alphabet pasta soup securely.",
      "The soup with letters is tucked inside the basket.",
      "Please find the letter-infused broth in the basket.",
      "The basket contains the noodle alphabet soup.",
      "The alphabet soup resides within the woven container.",
      "The basket holds the letter-themed noodle soup.",
      "The soup with tiny letters is inside the basket.",
      "Our beloved alphabet soup is placed in the basket.",
      "The basket securely holds the noodle-letter broth.",
      "The letter soup is resting in the container.",
      "Look for the alphabet pasta soup inside the basket.",
      "The basket holds the soup with letter characters.",
      "Please note the alphabet-themed broth in the basket.",
      "The letter-infused noodle soup is in the basket.",
      "The basket contains the beloved alphabet soup.",
      "The alphabet broth with letter noodles is in the basket.",
      "Please find the letter-themed soup inside the container.",
      "The basket holds the noodle-letter soup securely.",
      "The letter-filled broth is resting in the basket.",
      "Look inside the basket for the alphabet soup.",
      "The basket holds the soup with letter pasta.",
      "Please notice the alphabet noodle soup in the basket.",
      "The letter-themed soup is in the woven container.",
      "The basket securely contains the alphabet soup.",
      "The soup with letter characters is in the basket.",
      "The basket holds the beloved letter broth.",
      "The alphabet pasta soup is resting in the basket.",
      "The letter-infused broth is in the container.",
      "Please observe the noodle-letter soup in the basket.",
      "The basket contains the soup with alphabet shapes.",
      "Look in the basket for the letter-themed broth.",
      "The alphabet noodle soup is in the container.",
      "The basket securely holds the letter-filled soup.",
      "The letter broth is resting inside the basket.",
      "The basket contains the alphabet pasta soup.",
      "The soup with letter characters is in the woven container.",
      "The basket securely holds the noodle-letter broth.",
      "The alphabet-themed soup is in the basket.",
      "The letter-filled broth is in the container.",
      "Please find the alphabet soup in the basket.",
      "The basket contains the soup with letter pasta.",
      "The alphabet noodle soup is resting in the basket.",
      "The letter-themed broth is in the woven container."
  ]
}