model_name:
save_video: True
ts_mode: eval
use_mp: False

experiment_dir:
device: "cuda"
benchmark_name:
folder: dataset-path
bddl_folder: "LIBERO/libero/libero/bddl_files/"
init_states_folder: "LIBERO/libero/libero/init_files/"
eval_spec_modalities:
task_id: 0  # if task_id is specified, it will only evaluate on that task

n_eval: 3
num_workers: ${n_eval}

# attack args
base_task_id:
target_task_id:
attack_method:

perturb_steps: 1024
alpha: 0.1
epsilon: 12 # 12
loss_type: "l2"
